DATA_BASE:
    ---Select_table---:
      name_db: Node
      fields:
        - None
      ref_fields: False
    Structure:
      name_db: Structure
      fields:
        - uid
        - struct_type
        - number
        - side
      ref_fields: False
    Node:
      name_db: Node
      fields:
        - uid
        - frame
        - stringer
        - side
        - coord_x
        - coord_y
        - coord_z
      ref_fields: True
      template: node_template.xlsx
      file_type:
        excel:
          fr_str_format
        bdf:
    Element:
      name_db: Element
      fields:
        - uid
        - element_ref
        - frame
        - stringer
        - side
        - nodes
        - property_id
      ref_fields: False
      template: element_template.xlsx
      file_type:
        excel:
          fr_str_format
        bdf:
    Mass:
      name_db: Mass
      fields:
        - uid
        - name
        - weight
        - frame
        - stringer
        - side
      ref_fields: True
      file_type:
        excel:
          fr_str_format
        bdf:
          - uid
          - coord_x
          - coord_y
          - coord_z
    Material:
      name_db: Material
      fields:
        - uid
        - type
        - density
        - eu
        - nu
      ref_fields: False
      template: material_template.xlsx
      file_type:
        excel:
          fr_str_format
        bdf:
    Sections:
      name_db: Section
      fields:
        - uid
        - type
        - frame
        - stringer
        - side
        - section_type
      ref_fields: True
      template: sections_template.xlsx
      file_type:
        excel:
          fr_str_format
    Section property:
      name_db: SectionProperty
      fields:
        - uid
        - type
        - area
        - inertia_zz
        - inertia_yy
        - inertia_zy
        - inertia_torsion
        - alpha
        - inertia_min
        - inertia_max
      ref_fields: True
      template: section_properties_template.xlsx
      file_type:
        excel:
          fr_str_format
    Element property:
      name_db: ElProperty
      fields:
        - uid
        - type
        - material_id
        - shell_thick
        - section_start
        - section_end
      ref_fields: False
      file_type:
        excel:
          fr_str_format
        bdf:
          - property_start
          - property_end
    Section property map:
      name_db: SectionPropertyMap
      fields:
        - sec_prop_uid
        - frame
        - stringer
        - side
      ref_fields: True
      file_type:
        excel:
          fr_str_format

    Sections_2:
      name_db: Section
      fields:
        - uid
        - type
        - frame
        - stringer
        - side
      dynamic_fields:
        section-type:
          ---Select_Section---:
            Class_name: None
            Parameters:
              - None
          Rectangular:
            Class_name: Square
            Parameters:
              - height
              - width_1
          I-Section:
            Class_name: ISection
            Parameters:
              - width_1
              - height
              - width_2
              - th_1
              - th_2
              - th_3
          L-Section:
            Class_name: AngleSection
            Parameters:
              - width_1
              - height
              - th_1
              - th_2
          C-Section:
            Class_name: CSection
            Parameters:
              - width_1
              - height
              - width_2
              - th_1
              - th_2
              - th_3
          Z-Section:
            Class_name: ZSection
            Parameters:
              - width_1
              - height
              - width_2
              - th_1
              - th_2
              - th_3
          FEM-Polygon:
            Class_name: FemPolygon
            Parameters:
              - y
              - z

    Stringer:
      name_db: Stringer
      fields:
        - number
        - side
      ref_fields: False
    Frame:
      name_db: Frame
      fields:
        - number
      ref_fields: False

WORK_TYPE:
    data_base:
      - name: Внести данные
        url_added: gfem/post_data
      - name: Получить данные
        url_added: gfem/get_data
      - name: Внести изменения
        url_added: gfem/update_data
      - name: Удалить данные
        url_added: gfem/delete_data
    services:
      - name: Расчет поперечных сечений
        url_added: stress-service/service_CS
      - name: Создать карту id
        url_added: stress-service/id-generate
      - name: Расчет нагрузок
        url_added: stress-service/
CALCULATION_TYPE:
  CROSS-SECTION:
    SECTION-TYPE:
      ---Select_Section---:
        Class_name: None
        Parameters:
          - None
      Rectangular:
        Class_name: Square
        Parameters:
          - height
          - width_1
      I-Section:
        Class_name: ISection
        Parameters:
          - width_1
          - height
          - width_2
          - th_1
          - th_2
          - th_3
      L-Section:
        Class_name: AngleSection
        Parameters:
          - width_1
          - height
          - th_1
          - th_2
      C-Section:
        Class_name: CSection
        Parameters:
          - width_1
          - height
          - width_2
          - th_1
          - th_2
          - th_3
      Z-Section:
        Class_name: ZSection
        Parameters:
          - width_1
          - height
          - width_2
          - th_1
          - th_2
          - th_3
      FEM-Polygon:
        Class_name: FemPolygon
        Parameters:
          - y
          - z
    STANDARD-PART:
      Parameters:
        - div_y
        - div_z
        - alpha
